### ISSUE TITLE
Scatterer effects and oceans disappear

### ISSUE THREAD

**Issue by ArcAios26** [OhioBob/Grannus-Expansion-Pack#6]
I am seeing an issue with scatterer atmosphere effects and oceans disappearing when GEP is installed. The current installation only has Kopernicus, EVE, scatterer, GPP, GPP_Secondary, GEP and OPM. I'm not sure where the problem actually is but it doesn't exist if you remove either OPM or GEP.

**Comment by OhioBob** [comment]
I suspect the problem is likely with GPP or GPP_Secondary.  Several updates and fixes have been made to the GPP scatterer configs and a new release is pending (should be very soon).  I've tested the particular installation that you describe with the updates and I've experienced no issues with the oceans, so hopefully the problem is fixed.
